// Generated by CoffeeScript 2.4.1
(function() {
  var app, cors, express, port;

  express = require('express');

  cors = require('cors');

  app = express();

  port = 3334;

  app.use(cors());

  app.use(express.json());

  app.use(express.static('public'));

  app.get('/', (req, res) => {
    return res.send('Hellod World!');
  });

  app.post('/reports', (req, res) => {
    console.log(req.body);
    return res.send('Hellod World!');
  });

  app.listen(port, () => {
    return console.log(`Example app listening on port ${port}!`);
  });

}).call(this);
